## Amnesty_article_coverage_analysis.R
##########################################################################
##
## Authors: Geoff Dancy and Christopher J. Fariss
##
## Title: "The Search for Human Rights: A Global Analysis Using Google Data"
##
## Contact Information: 
##  Geoff Dancy <gdancy@tulane.edu>
##  Christopher J. Fariss <cjf0006@gmail.com>
##  
##  Copyright (c) 2022, under the Creative Commons Attribution-Noncommercial-Share Alike 3.0 United States License.
## For more information see: http://creativecommons.org/licenses/by-nc-sa/3.0/us/
##  All rights reserved. 
##
##########################################################################

## load the HRPS with the additional information from the total number of amnesty reports generated by country each year
#data <- try(read.csv("Data_input/HumanRightsProtectionScores_v4.01_amnesty_report_count.csv"))

data <- try(read.csv("Data_input/HumanRightsProtectionScores_v4.01_amnesty_report_count_v2.csv"))

## inspect the object
head(data)
summary(data)
table(data$amnesty_report_count, data$YEAR)


# create an empty list
newdata <- list()

# take K draws from the posterior distribution and make K new datasets in the list object just created
for(j in 1:1000){
  newdata[[j]] <- data
  newdata[[j]]$draw <- rnorm(cbind(rep(1,nrow(data))), mean=data$theta_mean, sd=data$theta_sd)
}

## a vector and a list object to hold some stuff
year_cor <- c()
year_cor_draws <- list()

YEAR <- 1961:2019

## this code is slow but it works fine <shrugs>; make an lapply() version later
for(i in 1:length(YEAR)){
  temp <- c()
  year_cor[i] <- cor(data$theta_mean[data$YEAR==YEAR[i]], data$amnesty_report_count[data$YEAR==YEAR[i]], use="pairwise", method="spearman")
  for(j in 1:1000){
    temp[j] <- cor(newdata[[j]]$draw[newdata[[j]]$YEAR==YEAR[i]], newdata[[j]]$amnesty_report_count[newdata[[j]]$YEAR==YEAR[i]], use="pairwise", method="spearman")
  }
  year_cor_draws[[i]] <- temp
}

year_cor

## unlist and lapply some stats
year_cor_draw_mean <- unlist(lapply(year_cor_draws, mean))
year_cor_draw_ub <- unlist(lapply(year_cor_draws, quantile, .975))
year_cor_draw_lb <- unlist(lapply(year_cor_draws, quantile, .025))

## organize all the correlation estimates in a data.frame
dat <- data.frame(year=1961:2019, year_cor, year_cor_draw_mean, year_cor_draw_ub, year_cor_draw_lb)
dat

## create graph file
pdf("Rplots/HRPS_Amnesty_Yearly_Correlations.pdf", height=8, width=8)

## make a sweet plots
par(mar=c(4,4,4,1))
plot(dat$year, dat$year_cor_draw_mean, type="n", ylim=c(-1,1), main="Yearly Correlation between Human Rights Protection\nScores and Number of Amnesty International Reports", ylab="Spearman Correlation", xlab="Year")
abline(h=0.5, col=grey(.25), lty=2)
abline(h=0, col=grey(.25), lty=2)
abline(h=-0.5, col=grey(.25), lty=2)
for(i in 1:nrow(dat)){
  lines(c(dat$year[i], dat$year[i]), c(dat$year_cor_draw_lb[i], dat$year_cor_draw_ub[i]), col=grey(.25))
}
points(dat$year, dat$year_cor_draw_mean, pch=21, bg=grey(.9), col=grey(.25))

dev.off()

## check out the cross-tabs 
ctabs <- xtabs(data$amnesty_report_count ~ data$YEAR + data$country_name) 
ctabs
ctabs[,'Uganda']
ctabs[,'Guatemala']
ctabs[,'Argentina']
ctabs[,'United Kingdom']
